### ISSUE TITLE
Missing selector in postgres-deployment.yaml?

### ISSUE THREAD

**Issue by 4everinbeta** [burrsutter/9stepsawesome#31]
I'm getting the following error when I attempt to create the postgres-deployment.yaml

`error: error validating "postgres-deployment.yml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false`

I can ignore it for now but it seems like something that should be demonstrated to the current spec. Or am I (very likely) missing something?

**Comment by burrsutter** [comment]
I apologize for the confusion: That is an old apiVersion that I need to clean up.  Currently apiVersion for Deployment yaml is "apiVersion: apps/v1"

**Comment by springified** [comment]
I've added 

```
selector:
    matchLabels:
      app: postgres

```
and be able to create postgres pod. 


```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.5
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_DB
              value: postgresdb
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: adminS3cret
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            # mountPath within the container
            - name: postgres-pvc
              mountPath: "/var/lib/postgresql/data/:Z"
      volumes:
        # mapped to the PVC
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc
```

`
